name: 'terraform_test'

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  terraform:
    name: 'Terraform Validation and Plan'
    runs-on: ubuntu-latest
    # The permissions block is needed to grant read permissions to contents for forks.
    permissions:
     contents: read
     pull-requests: write
     statuses: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Set up Terraform (The version should be the one you are using)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.7.3'
      
      # Initialize Terraform
      - name: Terraform Initialize
        id: init
        run: terraform init
      
      # Validate Terraform files
      - name: Terraform Validate
        id: validate
        run: terraform validate